# Generated by Django 5.2.12 on 2026-04-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('client_id', models.CharField(editable=False, max_length=24, unique=True)),
                ('description', models.TextField(blank=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('secret_prefix', models.CharField(blank=True, editable=False, max_length=12)),
                ('secret_hash', models.CharField(blank=True, editable=False, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
