# Generated by Django 5.2.12 on 2026-03-31 18:49

from django.db import migrations

def fill_sku(apps, schema_editor):
    Product = apps.get_model('products', 'Product')

    for product in Product.objects.filter(sku__isnull=True):
        product.sku = f"SKU-{product.id:05d}"
        product.save(update_fields=["sku"])

def reverse_fill_sku(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Product.objects.filter(sku__startswith="SKU-").update(sku=None)

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_sku'),
    ]

    operations = [
        migrations.RunPython(fill_sku, reverse_fill_sku),
    ]
